### ISSUE TITLE
Cannot find `system.edn` when requiring generator

### ISSUE THREAD

**Issue by sheluchin** [zmedelis/bosquet#40]
It looks like something broke in the latest release and I can no longer require `bosquet.llm.generator`. It worked in the previous version:

```shell
$ clj -Sdeps '{:deps {io.github.zmedelis/bosquet {:mvn/version "v2023.10.11"}}}}'
Downloading: net/minidev/json-smart/maven-metadata.xml from central
Clojure 1.11.1
user=> (require '[bosquet.llm.generator :as g])
WARNING: Unable to resolve "#ref [:config :azure-openai-api-endpoint]" at [[:llm/openai :provider/azure] :api-endpoint :form 0]
2023-11-10T19:01:43.560Z xps INFO [bosquet.system:72] - Initializing Bosquet resources:
2023-11-10T19:01:43.586Z xps INFO [bosquet.system:65] -  * Short term memory with ({:encoder :memory.encoding/as-is})
2023-11-10T19:01:43.590Z xps INFO [bosquet.system:51] -  * OpenAI API service (openai)
nil
user=> 
```

but not in latest:
```shell
$ clj -Sdeps '{:deps {io.github.zmedelis/bosquet {:mvn/version "v2023.10.31"}}}}'
Clojure 1.11.1
user=> (require '[bosquet.llm.generator :as g])
Execution error (FileNotFoundException) at java.io.FileInputStream/open0 (FileInputStream.java:-2).
system.edn (No such file or directory)
user=> (.printStackTrace *e)
Syntax error macroexpanding at (system.clj:63:3).
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3719)
	at clojure.lang.Compiler$DefExpr.eval(Compiler.java:457)
	at clojure.lang.Compiler.eval(Compiler.java:7199)
	at clojure.lang.Compiler.load(Compiler.java:7653)
	at clojure.lang.RT.loadResourceScript(RT.java:381)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.load(RT.java:459)
	at clojure.lang.RT.load(RT.java:424)
	at clojure.core$load$fn__4621.invoke(core.clj:6161)
	at clojure.core$load.invokeStatic(core.clj:6160)
	at clojure.core$load.doInvoke(core.clj:6144)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5933)
	at clojure.core$load_one.invoke(core.clj:5928)
	at clojure.core$load_lib$fn__4563.invoke(core.clj:5975)
	at clojure.core$load_lib.invokeStatic(core.clj:5974)
	at clojure.core$load_lib.doInvoke(core.clj:5953)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$apply.invoke(core.clj:662)
	at clojure.core$load_libs.invokeStatic(core.clj:6017)
	at clojure.core$load_libs.doInvoke(core.clj:6000)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$apply.invoke(core.clj:662)
	at clojure.core$require.invokeStatic(core.clj:6106)
	at clojure.core$require.doInvoke(core.clj:6038)
	at clojure.lang.RestFn.invoke(RestFn.java:619)
	at bosquet.complete$eval2675$loading__1607__auto____2676.invoke(complete.clj:1)
	at bosquet.complete$eval2675.invokeStatic(complete.clj:1)
	at bosquet.complete$eval2675.invoke(complete.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7194)
	at clojure.lang.Compiler.eval(Compiler.java:7183)
	at clojure.lang.Compiler.load(Compiler.java:7653)
	at clojure.lang.RT.loadResourceScript(RT.java:381)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.load(RT.java:459)
	at clojure.lang.RT.load(RT.java:424)
	at clojure.core$load$fn__1742.invoke(core.clj:6161)
	at clojure.core$load.invokeStatic(core.clj:6160)
	at clojure.core$load.doInvoke(core.clj:6144)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5933)
	at clojure.core$load_one.invoke(core.clj:5928)
	at clojure.core$load_lib$fn__1684.invoke(core.clj:5975)
	at clojure.core$load_lib.invokeStatic(core.clj:5974)
	at clojure.core$load_lib.doInvoke(core.clj:5953)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$apply.invoke(core.clj:662)
	at clojure.core$load_libs.invokeStatic(core.clj:6017)
	at clojure.core$load_libs.doInvoke(core.clj:6000)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$apply.invoke(core.clj:662)
	at clojure.core$require.invokeStatic(core.clj:6106)
	at clojure.core$require.doInvoke(core.clj:6038)
	at clojure.lang.RestFn.invoke(RestFn.java:805)
	at bosquet.llm.generator$eval2669$loading__1607__auto____2670.invoke(generator.clj:1)
	at bosquet.llm.generator$eval2669.invokeStatic(generator.clj:1)
	at bosquet.llm.generator$eval2669.invoke(generator.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7194)
	at clojure.lang.Compiler.eval(Compiler.java:7183)
	at clojure.lang.Compiler.load(Compiler.java:7653)
	at clojure.lang.RT.loadResourceScript(RT.java:381)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.load(RT.java:459)
	at clojure.lang.RT.load(RT.java:424)
	at clojure.core$load$fn__1742.invoke(core.clj:6161)
	at clojure.core$load.invokeStatic(core.clj:6160)
	at clojure.core$load.doInvoke(core.clj:6144)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5933)
	at clojure.core$load_one.invoke(core.clj:5928)
	at clojure.core$load_lib$fn__1684.invoke(core.clj:5975)
	at clojure.core$load_lib.invokeStatic(core.clj:5974)
	at clojure.core$load_lib.doInvoke(core.clj:5953)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$apply.invoke(core.clj:662)
	at clojure.core$load_libs.invokeStatic(core.clj:6017)
	at clojure.core$load_libs.doInvoke(core.clj:6000)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$apply.invoke(core.clj:662)
	at clojure.core$require.invokeStatic(core.clj:6106)
	at clojure.core$require.doInvoke(core.clj:6038)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at user$eval2530.invokeStatic(NO_SOURCE_FILE:1)
	at user$eval2530.invoke(NO_SOURCE_FILE:1)
	at clojure.lang.Compiler.eval(Compiler.java:7194)
	at clojure.lang.Compiler.eval(Compiler.java:7149)
	at clojure.core$eval.invokeStatic(core.clj:3215)
	at clojure.core$eval.invoke(core.clj:3211)
	at clojure.main$repl$read_eval_print__9206$fn__9209.invoke(main.clj:437)
	at clojure.main$repl$read_eval_print__9206.invoke(main.clj:437)
	at clojure.main$repl$fn__9215.invoke(main.clj:458)
	at clojure.main$repl.invokeStatic(main.clj:458)
	at clojure.main$repl_opt.invokeStatic(main.clj:522)
	at clojure.main$main.invokeStatic(main.clj:667)
	at clojure.main$main.doInvoke(main.clj:616)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.main.main(main.java:40)
Caused by: java.io.FileNotFoundException: system.edn (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at clojure.java.io$fn__11617.invokeStatic(io.clj:229)
	at clojure.java.io$fn__11617.invoke(io.clj:229)
	at clojure.java.io$fn__11569$G__11523__11576.invoke(io.clj:69)
	at clojure.java.io$fn__11629.invokeStatic(io.clj:258)
	at clojure.java.io$fn__11629.invoke(io.clj:254)
	at clojure.java.io$fn__11569$G__11523__11576.invoke(io.clj:69)
	at clojure.java.io$fn__11591.invokeStatic(io.clj:165)
	at clojure.java.io$fn__11591.invoke(io.clj:165)
	at clojure.java.io$fn__11530$G__11519__11537.invoke(io.clj:69)
	at clojure.java.io$reader.invokeStatic(io.clj:102)
	at clojure.java.io$reader.doInvoke(io.clj:86)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at aero.core$read_config_into_tagged_literal.invokeStatic(core.cljc:194)
	at aero.core$read_config_into_tagged_literal.invoke(core.cljc:191)
	at aero.core$read_config.invokeStatic(core.cljc:426)
	at aero.core$read_config.invoke(core.cljc:414)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3714)
	... 105 more
nil
user=> 
```

**Comment by zmedelis** [comment]
@sheluchin please try now with the latest release
`io.github.zmedelis/bosquet {:mvn/version "v2023.11.21"}`

Note that if you do not have `config.edn` with API keys it will fail, but now with proper error message.

**Comment by sheluchin** [comment]
Thank you, @zmedelis. Looks like latest fixes it.
